field.storage_settings.task_field_task:
  type: mapping
  label: Task storage settings
  mapping:
    fo_field:
      type: string
      label: Fo_field

field.field_settings.task_field_task:
  type: mapping
  label: Task field settings
  mapping:
    active:
      type: string
      label: Active


field.formatter.settings.task_field_task:
  type: mapping
  label: Task formatter settings
  mapping:
    fo_formatter:
      type: string
      label: Fo_formatter

field.widget.settings.task_field_task_field_default:
  type: mapping
  label: Task Field Default widget settings
  mapping:
    fo_settings:
      type: string
      label: Fo_widget

# Field storage.
field.storage_settings.task_field_parameters:
  type: mapping
  label: Example storage settings
  mapping:
    foo:
      type: string
      label: Foo

# Field instance.
field.field_settings.task_field_parameters:
  type: mapping
  label: Example field settings
  mapping:
    bar:
      type: string
      label: Bar

# Default value.
field.value.task_field_parameters:
  type: mapping
  label: Default value
  mapping:
    deadline:
      type: datetime
      label: Deadline
    status:
      type: string
      label: status
    timer:
      type: boolean
      label: Timer

# Field widget.
field.widget.settings.task_field_parameters:
  type: mapping
  label: Example widget settings
  mapping:
    foo:
      type: string
      label: Foo

# Field formatter.
field.formatter.settings.task_field_parameters_default:
  type: mapping
  label: Example formatter settings
  mapping:
    foo:
      type: string
      label: Foo
