# Task Field
field.storage_settings.task_field_task:
  type: mapping
  label: Task storage settings
  mapping:
    priority_options:
      type: sequence
      label: Priority options
      sequence:
        type: string
        label: Priority label
    status_options:
      type: sequence
      label: Status options
      sequence:
        type: string
        label: Status label

field.field_settings.task_field_task:
  type: mapping
  label: Task field settings
  mapping:
    default_priority:
      type: integer
      label: Default priority
    default_status:
      type: string
      label: Default status

field.formatter.settings.task_field_task:
  type: mapping
  label: Task formatter settings
  mapping:
    display_format:
      type: string
      label: Display format

field.widget.settings.task_field_task_field_default:
  type: mapping
  label: Task Field Default widget settings
  mapping:
    display_timer:
      type: boolean
      label: Display timer

# Progress Field
field.storage_settings.task_field_progress:
  type: mapping
  label: Progress storage settings
  mapping:
    priority_options:
      type: sequence
      label: Priority options
      sequence:
        type: string
        label: Priority label
    status_options:
      type: sequence
      label: Status options
      sequence:
        type: string
        label: Status label

field.field_settings.task_field_progress:
  type: mapping
  label: Progress field settings
  mapping:
    default_priority:
      type: integer
      label: Default priority
    default_status:
      type: string
      label: Default status

field.value.task_field_progress:
  type: mapping
  label: Default value
  mapping:
    priority:
      type: integer
      label: Priority
    timer:
      type: boolean
      label: Timer
    status:
      type: string
      label: Status
    deadline:
      type: datetime_iso8601
      label: Deadline

field.widget.settings.task_field_progress:
  type: mapping
  label: Progress widget settings
  mapping:
    display_timer:
      type: boolean
      label: Display timer

field.formatter.settings.task_field_progress_default:
  type: mapping
  label: Progress formatter settings
  mapping:
    display_format:
      type: string
      label: Display format

# Parameters Field (if still needed)
field.storage_settings.task_field_parameters:
  type: mapping
  label: Parameters storage settings
  mapping:
    parameter_options:
      type: sequence
      label: Parameter options
      sequence:
        type: string
        label: Parameter label

field.field_settings.task_field_parameters:
  type: mapping
  label: Parameters field settings
  mapping:
    default_parameter:
      type: string
      label: Default parameter

field.value.task_field_parameters:
  type: mapping
  label: Default value
  mapping:
    deadline:
      type: datetime_iso8601
      label: Deadline
    status:
      type: string
      label: Status
    timer:
      type: boolean


























































      label: Timer

field.widget.settings.task_field_parameters:
  type: mapping
  label: Parameters widget settings
  mapping:
    display_format:
      type: string
      label: Display format

field.formatter.settings.task_field_parameters_default:
  type: mapping
  label: Parameters formatter settings
  mapping:
    display_format:
      type: string
      label: Display format
